### ISSUE TITLE
Consider removing required import map

### ISSUE THREAD

**Issue by bartlomieju** [galkowskit/denofun#20]
First of all; awesome lib! 

Readme says:

> Code samples assume import map is configured like this.
```
{
  "imports": {
    "std/": "std/",
    "denofun/": "https://raw.githubusercontent.com/galkowskit/denofun/master/"
  }
}
```

I'd suggest to consider removing this requirement. Using external library shouldn't require user to create an import map just to use that library. Besides Deno currently supports only single import map which might have conflict with required "std/" remapping (eg. user pins specific version of standard library.

I suggest replacing require import map with simple `deps.ts` file where all external imports are done. Example: https://github.com/buildondata/deno-postgres/blob/master/deps.ts

**Comment by galkowskit** [comment]
It's not a requirement, it's more of a suggestion and it's to simplify imports in the docs. The library as it stands has no external dependencies outside of `deno_std` for testing.

But I agree. I'll remove this whole section and the importmap in favour of `deno.land/x/` though since it got added there. :)

**Comment by galkowskit** [comment]
^ Import maps are unnecessary. Removed in favour of deno.land/x/ links. :)
