### ISSUE TITLE
Don't use curry by default

### ISSUE THREAD

**Issue by KSXGitHub** [galkowskit/denofun#26]
## Why?

1. Most of the time I don't need curried function, and I don't want to pay what I don't use.
2. Once [partial application proposal](https://github.com/tc39/proposal-partial-application) is accepted, curry would be unnecessary.
3. It messes up type information.

**Comment by galkowskit** [comment]
I was actually thinking about it recently. The original goal was to get autocurriable functions because the deno_std library is already great but it didn't provide curry possibilities. 

After a while my main point of frustration was that curry makes all the types lost. It might be a good idea to provide curry function and let end-users decide if they want to use it, potentially even with deno_std functions. I haven't even thought about your argument number two. That's a very solid one though.

I think I'll remove curry by default, it might be causing more problems than it's worth. 👍
